// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GroupPermissionsController from "./group_permissions_controller"
application.register("group-permissions", GroupPermissionsController)

import ScoreboardController from "./scoreboard_controller"
application.register("scoreboard", ScoreboardController)

import ScoringController from "./scoring_controller"
application.register("scoring", ScoringController)
