// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ChallengeSortingController from "./challenge_sorting_controller"
application.register("challenge-sorting", ChallengeSortingController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import StatisticsController from "./statistics_controller"
application.register("statistics", StatisticsController)
